CCC-4 ✅ test: test

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,31 +1,84 @@
-COMMIT_MESSAGE_FILE=$1
-COMMIT_MESSAGE=$(cat "$COMMIT_MESSAGE_FILE")
+COMMIT_MSG_FILE=$1
+ORIGINAL_COMMIT_MSG=$(cat $COMMIT_MSG_FILE)
+COMMIT_MSG=$(cat $COMMIT_MSG_FILE)
 
-# Jira 티켓 번호와 이모티콘 제거
-CLEANED_COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE" | sed -E 's/^[A-Z]+-[0-9]+ //')
-CLEANED_COMMIT_MESSAGE=$(echo "$CLEANED_COMMIT_MESSAGE" | sed -E 's/^(✨|🐛|🔨|📝|💄|🔀|🚚|🎨|♻️|🔥|✅|📦) //')
+# ----------------------------------- 형식검증 -----------------------------------
 
 # 커밋 메시지 형식 검증 (영어 소문자로 시작하고 콜론과 공백 포함 여부)
-if ! echo "$CLEANED_COMMIT_MESSAGE" | grep -qE "^[a-z]+: "; then
+if ! echo "$ORIGINAL_COMMIT_MSG" | grep -qE "^[a-z]+: "; then
   echo
   echo "------------------------ERROR------------------------"
   echo "🥵 커밋 메시지는 영어 소문자로 시작하고 콜론과 공백이 뒤따라야 합니다.🥵"
   echo "🍙 <type>(<scope: 선택>): <short summary> 🍙"
-  echo "❗️ (현재 커밋 메세지) $CLEANED_COMMIT_MESSAGE ❗️"
+  echo "❗️ (현재 커밋 메세지) $ORIGINAL_COMMIT_MSG ❗️"
   exit 1
 fi
 
 # 커밋 메시지 제목 길이 검증
-FIRST_LINE=$(echo "$COMMIT_MESSAGE" | head -n 1)
+FIRST_LINE=$(echo "$ORIGINAL_COMMIT_MSG" | head -n 1)
 FIRST_LINE_LENGTH=$(echo -n "$FIRST_LINE" | wc -m)
 
-if [ "$FIRST_LINE_LENGTH" -gt 60 ]; then
+if [ "$FIRST_LINE_LENGTH" -gt 50 ]; then
   echo
   echo "------------------------ERROR------------------------"
-  echo "🥵 커밋 메시지의 제목은 60자를 넘을 수 없습니다.🥵"
-  echo "❗️❗️ (현재 길이) $FIRST_LINE_LENGTH ❗️❗️"
+  echo "🥵 커밋 메시지의 제목은 50자를 넘을 수 없습니다.🥵"
+  echo "❗️❗️ (현재) $FIRST_LINE_LENGTH 글자 ❗️❗️"
   exit 1
 fi
 
+# ----------------------------------- 커밋 포맷팅 -----------------------------------
+
+echo
+echo '✈️ ✈️ ✈️ 🛫 wait add jira issue number & Gitmoji 🛬 ✈️ ✈️ ✈️'
+
+BRANCH_NAME=$(git symbolic-ref -q HEAD)
+BRANCH_NAME=${BRANCH_NAME##*/} # Remove everything before the last /
+ISSUE_TICKET=$(echo "$BRANCH_NAME" | sed -n 's/^\([A-Z]*-[0-9]*\)-\(.*\)$/\1/p')
+
+# 이모지 맵
+case "$ORIGINAL_COMMIT_MSG" in
+    feat*) EMOJI="✨";;
+    fix*|!HOTFIX*) EMOJI="🐛";;
+    build*) EMOJI="🔨";;
+    docs*) EMOJI="📝";;
+    design*) EMOJI="💄";;
+    merge*) EMOJI="🔀";;
+    rename*) EMOJI="🚚";;
+    style*) EMOJI="🎨";;
+    refactor*) EMOJI="♻️";;
+    remove*) EMOJI="🔥";;
+    test*) EMOJI="✅";;
+    chore*) EMOJI="📦";;
+    *) 
+      echo
+      echo "------------------------ERROR------------------------"
+      echo "🥵 허용되는 커밋메세지 타입을 입력해주세요(대소문자구분) 🥵"
+      echo "👌 feat,fix,!HOTFIX,build,docs,design,merge,rename,style,refactor,remove,test,chore 👌"
+      exit 1
+      ;;
+esac
+
+# 이모지 추가
+if [ -n "$EMOJI" ]; then
+    COMMIT_MSG="$EMOJI $COMMIT_MSG"
+fi
+
+
+# Check if ISSUE_TICKET is not empty
+if [ -n "$ISSUE_TICKET" ]; then
+  # Prepend Jira 이슈 티켓 번호 to the commit message with a hyphen and remove the space
+  COMMIT_MSG="$ISSUE_TICKET $COMMIT_MSG"
+   echo "       Jira 이슈 티켓 번호: $ISSUE_TICKET / emoji $EMOJI      "
+   echo
+else
+    COMMIT_MSG="$COMMIT_MSG"
+    echo "       Jira 이슈 티켓 번호: ⚠️ 없어요 ⚠️ / emoji $EMOJI      "
+    echo
+fi
+
+
+echo "$COMMIT_MSG" > $COMMIT_MSG_FILE
+
+echo
 echo "🔆 Thanks for keeping the convention 🔆"
 echo
