✨ CCC-4-feat: dfs

diff --git a/.husky/prepare-commit-msg b/.husky/prepare-commit-msg
--- a/.husky/prepare-commit-msg
+++ b/.husky/prepare-commit-msg
@@ -1,48 +1,27 @@
-; #!/usr/bin/env sh
-; . "$(dirname -- "$0")/_/husky.sh"
-
-; echo 'wait add jira issue number we found from branch name'
-
-; BRANCH_NAME=$(git symbolic-ref -q HEAD)
-; BRANCH_NAME=${BRANCH_NAME##*/} # Remove everything before the last /
-; ISSUE_TICKET=$(echo "$BRANCH_NAME" | sed -n 's/^\([A-Z]*-[0-9]*\)-\(.*\)$/\1/p')
-
-; # Check if ISSUE_TICKET is not empty
-; if [ -n "$ISSUE_TICKET" ]; then
-; # Output extracted Jira 이슈 티켓 번호
-; echo "Extracted Jira 이슈 티켓 번호: $ISSUE_TICKET"
-
-; # Read the commit message from the temporary file
-; COMMIT_MSG_FILE=$1
-; COMMIT_MSG=$(cat $COMMIT_MSG_FILE)
-
-; # Prepend Jira 이슈 티켓 번호 to the commit message with a hyphen and remove the space
-; echo "$ISSUE_TICKET-$COMMIT_MSG" > $COMMIT_MSG_FILE
-; fi
-
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
-
-echo 'wait add jira issue number we found from branch name'
+echo
+echo '✈️ ✈️ ✈️ 🛫 wait add jira issue number & EMOJI 🛬 ✈️ ✈️ ✈️'
 
 BRANCH_NAME=$(git symbolic-ref -q HEAD)
 BRANCH_NAME=${BRANCH_NAME##*/} # Remove everything before the last /
 ISSUE_TICKET=$(echo "$BRANCH_NAME" | sed -n 's/^\([A-Z]*-[0-9]*\)-\(.*\)$/\1/p')
 
-# Check if ISSUE_TICKET is not empty
-if [ -n "$ISSUE_TICKET" ]; then
-  # Output extracted Jira 이슈 티켓 번호
-  echo "Extracted Jira 이슈 티켓 번호: $ISSUE_TICKET"
-
   # Read the commit message from the temporary file
   COMMIT_MSG_FILE=$1
+  ORIGINAL_COMMIT_MSG=$(cat $COMMIT_MSG_FILE)
   COMMIT_MSG=$(cat $COMMIT_MSG_FILE)
 
+# Check if ISSUE_TICKET is not empty
+if [ -n "$ISSUE_TICKET" ]; then
   # Prepend Jira 이슈 티켓 번호 to the commit message with a hyphen and remove the space
   COMMIT_MSG="$ISSUE_TICKET-$COMMIT_MSG"
+else
+    COMMIT_MSG="$COMMIT_MSG"
+    echo "⚠️ ⚠️ Jira 이슈 티켓 번호가 없어요 ⚠️ ⚠️ "
+    echo
+fi
 
   # 이모지 맵
-  case "$COMMIT_MSG" in
+  case "$ORIGINAL_COMMIT_MSG" in
     feat*) EMOJI="✨";;
     fix*|!HOTFIX*) EMOJI="🐛";;
     build*) EMOJI="🔨";;
@@ -55,13 +34,21 @@ if [ -n "$ISSUE_TICKET" ]; then
     remove*) EMOJI="🔥";;
     test*) EMOJI="✅";;
     chore*) EMOJI="📦";;
-    *) EMOJI="";;
+    *) 
+      echo
+      echo "------------------------ERROR------------------------"
+      echo "🥵 허용되는 커밋메세지 타입을 입력해주세요(대소문자구분) 🥵"
+      echo "👌 feat,fix,build,docs,design,merge,rename,style,refactor,remove,test,chore 👌"
+      exit 1
+      ;;
   esac
 
   # 이모지 추가
   if [ -n "$EMOJI" ]; then
-    COMMIT_MSG="$EMOJI $COMMIT_MSG"
+    COMMIT_MSG="$EMOJI$COMMIT_MSG"
+    echo "       Jira 이슈 티켓 번호: $ISSUE_TICKET / emoji $EMOJI      "
+    echo
   fi
 
   echo "$COMMIT_MSG" > $COMMIT_MSG_FILE
-fi
+
